homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('Johanes_profile1/', views.profile1, name='profile1'),
    path('Johanes_profile2/', views.profile2, name='profile2'),
    path('Johanes_favorite/', views.myfavorite, name='myfavorite'),
    path('Johanes_Social_Media/', views.socialmedia, name='socialmedia'),
    path('navbar/',views.navbar, name='navbar'),
    path('HomeStory1/', views.homeStory1, name='homeStory1'),
    path('AboutMe/', views.aboutme, name='aboutme'),
    path('MyContact/', views.mycontact, name='mycontact')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
# UNTUK STORY 3
def home(request):
    return render(request, 'home.html')

def profile1(request):
    return render(request, 'profile1.html')

def profile2(request):
    return render(request, 'profile2.html')

def myfavorite(request):
    return render(request, 'myfavorite.html')

def socialmedia(request):
    return render(request, 'socialmedia.html')

def navbar(request):
    return render(request, 'navbar.html')

#UNTUK STORY 1
def homeStory1(request):
    return render(request, 'homeStory1.html')

def aboutme(request):
    return render(request, 'aboutme.html')

def mycontact(request):
    return render(request, 'mycontact.html')

homepage/templates/aboutme.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<!-- Untuk background foto yang blur sumber nya https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_blurred_bg -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>
	About Me - Johanes Marihot Perkasa Simarmata
</title>
<style>
  body, html {
    height: 100%;
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
  }
  h3{
			color: white;
			text-align: left;
			font-size: 20px;
			font-family: cursive;
		}

  * {
    box-sizing: border-box;
  }

  .bg-image {
    background-image: url("/static/programmer.jpg");
    filter: blur(8px);
    -webkit-filter: blur(8px);
    height: 100%; 
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

  .bg-text {
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.4);
    color: white;
    font-weight: bold;
    border: 3px solid #f1f1f1;
    position: absolute;
    top: 60%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 2;
    width: 80%;
    padding: 20px;
    text-align: center;
  }
  header{
    width: 100%
    height: 70px;
    background-color: black;
  }
  ul{
    width: auto;
    float: center;
    margin-top: 7px;
  }
  li{
    display: inline-block;
    padding: 15px 30px;
  }
  a{
    text-align: center;
    color: white;
    text-decoration: none;
    font-family: monospace;
  }
  a:hover{
    color: yellow;
  }
</style>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><a href="{% url 'homepage:homeStory1'%}">Home</a></li>
        <li><a href="{% url 'homepage:aboutme' %}">About Me</a></li>
        <li><a href="{% url 'homepage:mycontact' %}">My Contact</a></li>
      </ul>
    </nav>
  </header>
  <div class="bg-image"></div>
  <div class="bg-text">
  	<h3 style="color: #b3ffff"><i><u>Biodata Singkat</u></i></h3>
    <table width="75%">
		<tr>
			<th><b>Nama Lengkap</b></th>
			<th>Johanes Marihot Perkasa Simarmata</th>
		</tr>
		<tr>
			<th><b>NPM</b></th>
			<th>1906308476</th>
		</tr>
		<tr>
			<th><b>Angkatan</b></th>
			<th><a href="https://maung.id/johanes.marihot"><b><i>MAUNG</i></b></a>(2019)</th>
		</tr>
		<tr>
			<th><b>Tempat Kuliah</b></th>
			<th>Fakultas Ilmu Komputer Universitas Indonesia</th>
		</tr>
		<tr>
			<th><b>Hobi</b></th>
			<th>Bermain video games</th>
		</tr>
	</table>
	<h3 style="color: #b3ffff"><i><u>Deskripsi Tentang Saya</u></i></h3>
	<h4>
		Saya lahir pada hari kamis tanggal 15 November 2001 di Bekasi tepatnya di Rumah Sakit Mitra Keluarga Bekasi Barat. Saya merupakan anak tunggal. Sebelum duduk di tempat kuliah sekarang, saya memiliki impian untuk berkuliah di Fakultas Teknik Mesin dan Dirgantara tepatnya di Institut Teknologi Bandung (ITB). Saya baru mengenal programming setelah saya dinyatakan lulus di tempat saya berkuliah sekarang.
	</h4>
	<h3 style="color: #b3ffff"><i><u>Riwayat Pendidikan</u></i></h3>
	<table width="75%">
		<tr>
			<th>2019-sekarang</th>
			<th>Universitas Indonesia</th>
		</tr>
		<tr>
			<th>2016-2019</th>
			<th>SMA Negeri 81 Jakarta</th>
		</tr>
		<tr>
			<th>2013-2016</th>
			<th>SMP Kristen 5 Penabur</th>
		</tr>
		<tr>
			<th>2007-2013</th>
			<th>SD Kristen Ceria Anak Bangsa</th>
		</tr>
	</table>
  </div>

</body>
</html>

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="style_base.css">
    <title>{% block title %}{% endblock %}</title>
    	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% block style %}
    	
    {% endblock %}

</head>

<body>
		{%block navbar %}

		{% endblock %}

        {% block isi %}

        {% endblock %}

</body>
</html>

homepage/templates/home.html
{% extends "base.html" %}

<!-- {% load static %}
 -->
	{% block title %}Home{% endblock %}
	{% block style %}
		<link rel="stylesheet" type="text/css" href="{% static 'stylehome.css' %}">	
    {% endblock %}
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> -->

	{%block isi%}
		{% include 'navbar.html' %}
	<div class="background">
		
 		<div class="container_adebe">
			<h2>Adebe</h2>
		</div>
		<div class="container1">
			<h3>Welcome to My Profile Page</h3>
		</div>
		<div class="container1a">
			<a href="{%url 'homepage:socialmedia'%}"><div class="oval">
				<h3>Contact</h3>
			</div></a>	
		</div>
		<div class="container1b">
			<a href="{% url 'homepage:profile1' %}"><div class="ovalExplore">
				<h3>EXPLORE --></h3>
			</div></a>
		</div>
	</div>
	{% endblock %}

homepage/templates/homeStory1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Home - Johanes Marihot Perkasa Simarmata</title>
<!-- Untuk background foto yang blur sumber nya https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_blurred_bg -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body, html {
    height: 100%;
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
  }

  * {
    box-sizing: border-box;
  }

  .bg-image {
    background-image: url("/static/programmer.jpg");
    filter: blur(8px);
    -webkit-filter: blur(8px);
    height: 100%; 
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

  .bg-text {
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.4);
    color: white;
    font-weight: bold;
    border: 3px solid #f1f1f1;
    position: absolute;
    top: 60%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 2;
    width: 80%;
    padding: 20px;
    text-align: center;
  }
  header{
    width: 100%
    height: 70px;
    background-color: black;
  }
  ul{
    width: auto;
    float: center;
    margin-top: 7px;
  }
  li{
    display: inline-block;
    padding: 15px 30px;
  }
  a{
    text-align: center;
    color: white;
    text-decoration: none;
    font-family: monospace;
  }
  a:hover{
    color: yellow;
  }
  .fotobentukbulat {
  vertical-align: middle;
  width: 140px;
  height: 150px;
  border-radius: 50%;
}
</style>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li>{% include 'navbar.html' %}</li>
        <li><a href="{% url 'homepage:homeStory1'%}">Home</a></li>
        <li><a href="{% url 'homepage:aboutme' %}">About Me</a></li>
        <li><a href="{% url 'homepage:mycontact' %}">My Contact</a></li>
      </ul>
    </nav>
  </header>
  <div class="bg-image"></div>
  <div class="bg-text">
    <h2>Welcome to my website!</h2>
    <img src="{% static 'fotoadebe1.jpg' %}" width="150px" class="fotobentukbulat">
    <h1 style="font-size:50px">I am Johanes Marihot Perkasa Simarmata</h1>
    <p>And I'm a Student Programmer</p>

</body>
</html>

homepage/templates/mycontact.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>My Contact - Johanes Marihot Perkasa Simarmata</title>
<script src="https://kit.fontawesome.com/a48052e337.js" crossorigin="anonymous"></script>
<!-- Untuk background foto yang blur sumber nya https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_blurred_bg -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body, html {
    height: 100%;
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
  }

  * {
    box-sizing: border-box;
  }

  .bg-image {
    background-image: url("/static/programmer.jpg");
    filter: blur(8px);
    -webkit-filter: blur(8px);
    height: 100%; 
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

  .bg-text {
    background-color: rgb(0,0,0);
    background-color: rgba(0,0,0, 0.4);
    color: white;
    font-weight: bold;
    border: 3px solid #f1f1f1;
    position: absolute;
    top: 60%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 2;
    width: 80%;
    padding: 20px;
    text-align: left;
  }
  header{
    width: 100%
    height: 70px;
    background-color: black;
  }
  ul{
    width: auto;
    float: center;
    margin-top: 7px;
  }
  li{
    display: inline-block;
    padding: 15px 30px;
  }
  a{
    font-size: 20px;
    text-align: center;
    color: white;
    text-decoration: none;
    font-family: monospace;
  }
  a:hover{
    color: yellow;
  }
  i{
    font-size: 40px;
  }
</style>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><a href="{% url 'homepage:homeStory1'%}">Home</a></li>
        <li><a href="{% url 'homepage:aboutme' %}">About Me</a></li>
        <li><a href="{% url 'homepage:mycontact' %}">My Contact</a></li>
      </ul>
    </nav>
  </header>
  <div class="bg-image"></div>
  <div class="bg-text">
    <h3 style="color: #b3ffff"><i><u>Social Media</u></i></h3>
    <table width="75%">
      <tr>
        <th>
          <a href="https://www.instagram.com/johanesimarmata/"><i class="fab fa-instagram"></i></a>
        </th>
        <th>
          <a href="https://www.instagram.com/johanesimarmata/">johanesimarmata</a>
        </th>
      </tr>
      <tr>
        <th>
          <a href="https://www.linkedin.com/in/johanes-marihot-perkasa-simarmata-7852a31a1/"><i class="fab fa-linkedin"></i></a>
        </th>
        <th>
          <a href="https://www.linkedin.com/in/johanes-marihot-perkasa-simarmata-7852a31a1/">Johanes Marihot Perkasa Simarmata</a>
        </th>
      </tr>
      <tr>
        <th>
          <a href="http://line.me/ti/p/~johanesimarmata"><i class="fab fa-line"></i></a>
        </th>
        <th>
          <a href="http://line.me/ti/p/~johanesimarmata">johanesimarmata</a>
        </th>
      </tr>
      <tr>
        <th>
          <a href="https://wa.me/628119505904"><i class="fab fa-whatsapp"></i></a>
        </th>
        <th>
          <a href="https://wa.me/628119505904">(+62)8119505904</a>
        </th>
      </tr>
      <tr>
        <th>
          <i class="far fa-envelope"></i>
        </th>
        <th>
          jmpsimarmata@gmail.com
        </th>
      </tr>
    </table>
    <h4>Or you can contact me via call or message in:</h4>
    <table width="75%">
      <tr>
        <th>
          <i class="fas fa-phone"></i>
        </th>
        <th>
          (+62)8119505904
        </th>
      </tr>
      <tr>
        <th>
          <i class="fas fa-sms"></i>
        </th>
        <th>
          (+62)8119505904
        </th>
      </tr>
    </table>
</body>
</html>

homepage/templates/myfavorite.html
{% extends "base.html" %}
{% load static %}

	{% block title %}All of My Favorites{% endblock %}
	{% block style %}
    	<link rel="stylesheet" type="text/css" href="{% static 'style3.css' %}">
    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% endblock %}

    {%block isi%}
	<div class="background", style="background-color: #EBEBEB;">
		<div class="container_adebe">
			<h2>Adebe</h2>
		</div>
		<div class="container1">
			<div class="fotopapa"></div>
			<div class="fotomama"></div>
		</div>
		<div class="container2">
			<div class="container2-a">
				<h2>Darwin Simarmata</h2>
				<h3>Gn.Para, 27 Februari 1992</h3>
				<h3>Wiraswasta</h3>
				<h3>Jakarta, Indonesia</h3>
			</div>
			<div class="container2-b">
				<h2>Endang Sihsetyaningrum</h2>
				<h3>Madiun, 18 Desember 1971</h3>
				<h3>Pegawai Negeri Sipil</h3>
				<h3>Jakarta, Indonesia</h3>
			</div>
			<div class="container2-c">
					<!-- Button trigger modal -->
				<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
				  Pemandangan yang kusuka
				</button>

				<!-- Modal -->
				<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h5 class="modal-title" id="exampleModalLabel">Indahnya Pemandangan</h5>
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
				      <div class="modal-body">
				        
				      	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
				  			<ol class="carousel-indicators">
						    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
						    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
						    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
				  			</ol>
				  			<div class="carousel-inner">
				    			<div class="carousel-item active">
				      				<img class="d-block w-100" src="https://images.unsplash.com/photo-1519501025264-65ba15a82390?ixlib=rb-1.2.1&w=1000&q=80" alt="Pemandangan Kota">
				      				<div class="carousel-caption d-none d-md-block">
				    					<h5>Pemandangan Kota di Sore Hari</h5>
				    					<p>Mobil-mobil berhenti di lampu merah dengan campuran langit yang sangat indah serta pemandangan gedung yang menarik.</p>
				  					</div>
				   				 </div>
				    			<div class="carousel-item">
				      				<img class="d-block w-100" src="https://images.pexels.com/photos/1236701/pexels-photo-1236701.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Indahnya kota">
				      				<div class="carousel-caption d-none d-md-block">
				    					<h5>Berjalan Kaki pada Sore Hari.</h5>
				    					<p>Seseorang berjalan di tengah jalan ditemani oleh matahari yang ingin terbenam dan pemandangan kota yang mulai menggelap</p>
				  					</div>
				    			</div>
				   				 <div class="carousel-item">
				      				<img class="d-block w-100" src="https://iphonewalls.net/wp-content/uploads/2014/09/Water%20Sunset%20Stars%20Lonely%20Man%20Walking%20iPhone%205%20Wallpaper-320x480.jpg" alt="Pemandangan pantai">
				      				<div class="carousel-caption d-none d-md-block">
				    					<h5>Berjalan di atas air.</h5>
				    					<p>Seseorang berjalan diatas air yang dangkal ditemani dengan pemandangan langit yang indah serta matahari yang ingin terbit</p>
				  					</div>
				    			</div>
				  			</div>
				  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				    <span class="carousel-control-next-icon" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>



				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
				        <button type="button" class="btn btn-primary">Simpan Cak</button>
				      </div>
				    </div>
				  </div>
				</div>
			</div>

			<div class="containertombol" style="top: 30%; right: 150%;">
				<a href="{% url 'homepage:profile2' %}"><img src="{% static 'chevron.png' %}" style="transform: rotate(180deg);"></a>
				<a href="{% url 'homepage:socialmedia' %}"><img src="{% static 'chevron.png' %}"></a>
			</div>
		</div>
		
	</div>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	{%endblock %}

homepage/templates/navbar.html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidebar {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
  line-height: 40px;
}

.sidebar a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidebar a:hover {
  color: #f1f1f1;
}

.sidebar .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
  background-color: #111;
  color: white;
  padding: 10px 15px;
  border: none;
}

.openbtn:hover {
  background-color: #444;
}



/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
</style>
</head>
<body>

<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <a href="{% url 'homepage:homeStory1' %}">Story 1</a>
  <a href="{% url 'homepage:home' %}">Story 3</a>
</div>

  <button class="openbtn" onclick="openNav()">☰ Open Sidebar</button>  

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
   
</body>
</html> 

homepage/templates/profile1.html
{% extends "base.html" %}
{%load static%}


	{% block title %}Profile - Johanes Marihot Perkasa Simarmata{% endblock %}
	{% block style %}
    	<link rel="stylesheet" type="text/css" href="{% static 'style1.css'%}">
    {% endblock %}

    {% block isi%}
	<div class="background", style="background-color: #EBEBEB;">
		<div class="container_adebe">
			<h2>Adebe</h2>
		</div>
		<div class="container1">
			<div class="fotoadebe"></div>
		</div>
		<div class="container2">
			<div class="container2-a">
				<h2>Biodata</h2>
				<h3>Name&emsp;&emsp; : Johanes Marihot Perkasa Simarmata</h3>
				<h3>Age&emsp;&emsp;&emsp;: 18 years old</h3>
				<h3>Location&emsp;: Jakarta, Indonesia</h3>
			</div>
			<div class="container2-b">
				<h2>About Me</h2>
				<span>I am a computer science student of University of Indonesia. I love listening to music, playing video games, and also playing with a code (like solving problems etc).</span>
			</div>
			<div class="container2-c">
				<h2>Education</h2>
				<h3>- Ceria Anak Bangsa Elementary School</h3>
				<h3>- Penabur Junior High School</h3>
				<h3>- 81 Senior High School</h3>
				<h3>- University of Indonesia</h3>
			</div>
					<div class="containertombol" style="top:-400px; left: 650px">
					<a href="{% url 'homepage:home' %}"><img src="{% static 'chevron.png' %}" style="transform: rotate(180deg);"></a>
					<a href="{% url 'homepage:profile2' %}"><img src="{% static 'chevron.png' %}"></a>
					</div>
		</div>
	</div>
	{%endblock %}

homepage/templates/profile2.html
{% extends "base.html" %}
{% load static %}

	{% block title %}Profile - Johanes Marihot Perkasa Simarmata{% endblock %}
	{% block style %}
    	<link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">
    {% endblock %}
<!-- 	<link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}"> -->


	{% block isi%}
	<div class="background", style="background-color: #EBEBEB;">
		<div class="container_adebe">
			<h2>Adebe</h2>
		</div>
		<div class="container1">
			<div class="fotoadebe"></div>
		</div>
		<div class="container2">
			<div class="container2-a">
				<h2>Personal Experience</h2>
				<h3>- Equipment division  Christmas celebration at 81 Senior High School </h3>
				<h3>- Equipment divison main coordinator of Christianity at Senior High School</h3>
				<h3>- Production divison of OLIM UI 2019</h3>
				<h3>- Equipment division of Fasilkom’s Graduation 2020</h3>
			</div>
			<div class="container2-b">
				<h2>Achievement</h2>
				<h3>Energizer Indonesia Robotic Master Cup (2012) at Senayan Trade Center</h3>
			</div>
			<div class="containertombol" style="top: 40%; right: 90%">
				<a href="{% url 'homepage:profile1' %}"><img src="{% static 'chevron.png' %}" style="transform: rotate(180deg);"></a>
				<a href="{% url 'homepage:myfavorite' %}"><img src="{% static 'chevron.png' %}"></a>
			</div>
		</div>
	</div>
	{%endblock%}

homepage/templates/socialmedia.html
{% extends "base.html" %}
{% load static %}
	<{% block title %}Social Media - Johanes Marihot Perkasa Simarmata{% endblock %}
<!-- 	<link rel="stylesheet" type="text/css" href="{% static 'style4.css' %}">
 -->{% block style %}
    	<link rel="stylesheet" type="text/css" href="{% static 'style4.css' %}">
    {% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	{%block isi%}
	<div class="container2"><div class="font2">Contact Me</div></div>
	<div class="background">
		<div class="container">
			<div class="containera">
				<img src="https://pluspng.com/img-png/instagram-png-instagram-icon-1600.png" width="50" height="50">
				<div class="font">
					johanesimarmata
				</div>
			</div>
			<div class="containerb">
				<img src="https://image.flaticon.com/icons/png/512/87/87386.png" width="50" height="50">
				<div class="font">
					johanesimarmata
				</div>
			</div>
			<div class="containera">
				<img src="https://cdn4.iconfinder.com/data/icons/aiga-symbol-signs/439/aiga_mail-512.png" width="50" height="40">
				<div class="font">
					jmpsimarmata@gmail.com
				</div>

			</div>
			<div class="containerb">
				<img src="https://cdn.onlinewebfonts.com/svg/img_286083.png" width="50" height="50">
				<div class="font">
					(+62)8119505904
				</div>
			</div>
			<div class="containertombol" style="top: 20%; right : -350px">
				<a href="{% url 'homepage:myfavorite' %}"><img src="{% static 'chevron.png' %}" style="transform: rotate(180deg);"></a>
			</div>
		</div>
	</div>
	{%endblock%}